# AUTOGENERATED FILE - PROVIDED BY WIREGUARD PORTAL
# WireGuard configuration: {{ .Peer.Identifier }}
# -WGP- PublicKey: {{ .Peer.PublicKey }}

[Interface]

# Core settings

PrivateKey = {{or .Peer.PrivateKey "<please-insert-your-private-key>" }}
Address = {{ .Peer.IPsStr }}

# Misc. settings (optional)
{{- if .Peer.DNSStr}}
DNS = {{ .Peer.DNSStr }}
{{- end}}
{{- if ne .Peer.Mtu 0}}
MTU = {{.Peer.Mtu}}
{{- end}}

{{- if .Interface.IsAdvancedSecurityEnabled}}
# AmneziaVPN settings
{{- if ne .Interface.AdvancedSecurity.JunkPacketCount 0}}
Jc = {{.Interface.AdvancedSecurity.JunkPacketCount}}
{{- end}}
{{- if ne .Interface.AdvancedSecurity.JunkPacketMinSize 0}}
Jmin = {{.Interface.AdvancedSecurity.JunkPacketMinSize}}
{{- end}}
{{- if ne .Interface.AdvancedSecurity.JunkPacketMaxSize 0}}
Jmax = {{.Interface.AdvancedSecurity.JunkPacketMaxSize}}
{{- end}}
{{- if ne .Interface.AdvancedSecurity.InitPacketJunkSize 0}}
S1 = {{.Interface.AdvancedSecurity.InitPacketJunkSize}}
{{- end}}
{{- if ne .Interface.AdvancedSecurity.ResponsePacketJunkSize 0}}
S2 = {{.Interface.AdvancedSecurity.ResponsePacketJunkSize}}
{{- end}}
{{- if ne .Interface.AdvancedSecurity.InitPacketMagicHeader 0}}
H1 = {{.Interface.AdvancedSecurity.InitPacketMagicHeader}}
{{- end}}
{{- if ne .Interface.AdvancedSecurity.ResponsePacketMagicHeader 0}}
H2 = {{.Interface.AdvancedSecurity.ResponsePacketMagicHeader}}
{{- end}}
{{- if ne .Interface.AdvancedSecurity.UnderloadPacketMagicHeader 0}}
H3 = {{.Interface.AdvancedSecurity.UnderloadPacketMagicHeader}}
{{- end}}
{{- if ne .Interface.AdvancedSecurity.TransportPacketMagicHeader 0}}
H4 = {{.Interface.AdvancedSecurity.TransportPacketMagicHeader}}
{{- end}}
{{- end}}

[Peer]
PublicKey = {{ .Interface.PublicKey }}
Endpoint = {{ .Peer.Endpoint }}
{{- if .Peer.AllowedIPsStr}}
AllowedIPs = {{ .Peer.AllowedIPsStr }}
{{- end}}
{{- if .Peer.PresharedKey}}
PresharedKey = {{ .Peer.PresharedKey }}
{{- end}}
{{- if ne .Peer.PersistentKeepalive 0}}
PersistentKeepalive = {{.Peer.PersistentKeepalive}}
{{- end}}