# AUTOGENERATED FILE - DO NOT EDIT
# This file uses wg-quick format.
# See https://man7.org/linux/man-pages/man8/wg-quick.8.html#CONFIGURATION
# Lines starting with the -WGP- tag are used by
# the WireGuard Portal configuration parser.

# -WGP- WIREGUARD PORTAL CONFIGURATION FILE
# -WGP- version {{ .Portal.Version }}

[Interface]
# -WGP- Peer: {{.Peer.Identifier}}
# -WGP- Created: {{.Peer.CreatedAt}}
# -WGP- Updated: {{.Peer.UpdatedAt}}
# -WGP- Display name: {{ .Peer.DisplayName }}
# -WGP- PublicKey: {{ .Peer.Interface.KeyPair.PublicKey }}
{{- if eq .Peer.Interface.Type "server"}}
# -WGP- Peer type: server
{{else}}
# -WGP- Peer type: client
{{- end}}

# Core settings
PrivateKey = {{ .Peer.Interface.KeyPair.PrivateKey }}
Address = {{ CidrsToString .Peer.Interface.Addresses }}

{{if .Peer.Interface.HasAdvancedSecurity }}
###############################
# AmneziaWG section
###############################
{{- $advSec := .Peer.Interface.AdvancedSecurity}}

# Junk settings
{{- if ne $advSec.JunkPacketCount 0}}
Jc = {{$advSec.JunkPacketCount}}
{{- end}}
{{- if ne $advSec.JunkPacketMinSize 0}}
Jmin = {{$advSec.JunkPacketMinSize}}
{{- end}}
{{- if ne $advSec.JunkPacketMaxSize 0}}
Jmax = {{$advSec.JunkPacketMaxSize}}
{{- end}}
{{- if ne $advSec.InitPacketJunkSize 0}}
S1 = {{$advSec.InitPacketJunkSize}}
{{- end}}
{{- if ne $advSec.ResponsePacketJunkSize 0}}
S2 = {{$advSec.ResponsePacketJunkSize}}
{{- end}}
{{- if ne $advSec.CookieReplyPacketJunkSize 0}}
S3 = {{$advSec.CookieReplyPacketJunkSize}}
{{- end}}
{{- if ne $advSec.TransportPacketJunkSize 0}}
S4 = {{ $advSec.TransportPacketJunkSize }}
{{- end}}

# Wireguard payload boundaries
H1 = {{$advSec.InitPacketMagicHeader}}
H2 = {{$advSec.ResponsePacketMagicHeader}}
H3 = {{$advSec.UnderloadPacketMagicHeader}}
H4 = {{$advSec.TransportPacketMagicHeader}}

# Custom junk settings
{{- if IsAwgString $advSec.FirstSpecialJunkPacket}}
I1 = {{ $advSec.FirstSpecialJunkPacket }}
{{- end}}
{{- if IsAwgString $advSec.SecondSpecialJunkPacket}}
I1 = {{ $advSec.SecondSpecialJunkPacket }}
{{- end}}
{{- if IsAwgString $advSec.ThirdSpecialJunkPacket}}
I1 = {{ $advSec.ThirdSpecialJunkPacket }}
{{- end}}
{{- if IsAwgString $advSec.FourthSpecialJunkPacket}}
I1 = {{ $advSec.FourthSpecialJunkPacket }}
{{- end}}
{{- if IsAwgString $advSec.FifthSpecialJunkPacket}}
I1 = {{ $advSec.FifthSpecialJunkPacket }}
{{- end}}

###############################
# End of AmneziaWG section
###############################
{{- end}}

# Misc. settings (optional)
{{- if .Peer.Interface.DnsStr.GetValue}}
DNS = {{ .Peer.Interface.DnsStr.GetValue }} {{- if .Peer.Interface.DnsSearchStr.GetValue}}, {{ .Peer.Interface.DnsSearchStr.GetValue }} {{- end}}
{{- end}}
{{- if ne .Peer.Interface.Mtu.GetValue 0}}
MTU = {{ .Peer.Interface.Mtu.GetValue }}
{{- end}}
{{- if ne .Peer.Interface.FirewallMark.GetValue 0}}
FwMark = {{ .Peer.Interface.FirewallMark.GetValue }}
{{- end}}
{{- if ne .Peer.Interface.RoutingTable.GetValue ""}}
Table = {{ .Peer.Interface.RoutingTable.GetValue }}
{{- end}}

# Interface hooks (optional)
{{- if .Peer.Interface.PreUp.GetValue}}
PreUp = {{ .Peer.Interface.PreUp.GetValue }}
{{- end}}
{{- if .Peer.Interface.PostUp.GetValue}}
PostUp = {{ .Peer.Interface.PostUp.GetValue }}
{{- end}}
{{- if .Peer.Interface.PreDown.GetValue}}
PreDown = {{ .Peer.Interface.PreDown.GetValue }}
{{- end}}
{{- if .Peer.Interface.PostDown.GetValue}}
PostDown = {{ .Peer.Interface.PostDown.GetValue }}
{{- end}}

[Peer]
PublicKey = {{ .Peer.EndpointPublicKey.GetValue }}
Endpoint = {{ .Peer.Endpoint.GetValue }}
{{- if .Peer.AllowedIPsStr.GetValue}}
AllowedIPs = {{ .Peer.AllowedIPsStr.GetValue }}
{{- end}}
{{- if .Peer.PresharedKey}}
PresharedKey = {{ .Peer.PresharedKey }}
{{- end}}
{{- if and (ne .Peer.PersistentKeepalive.GetValue 0) (eq .Peer.Interface.Type "client")}}
PersistentKeepalive = {{ .Peer.PersistentKeepalive.GetValue }}
{{- end}}
